alerting:
  alertmanagers:
  - static_configs: 
    - targets: 
      - 127.0.0.1:9093
global: {evaluation_interval: 1m, scrape_interval: 10s}
rule_files: 
  - "alertrule.yml"
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
- job_name: snmp
  metrics_path: /snmp
  params: {}
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - {replacement: '127.0.0.1:9116', target_label: __address__}
  static_configs: []
